version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../lambda.zip .
      - cd ..
      - zip -g lambda.zip lambda.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lambda-ApiFunction-O8zKYrFXyrB1 --zip-file fileb://lambda.zip
      - echo "DONE!!"